const workshopsInfos = [
  {
    id: 1,
    workshop: "Session 1",
    workshops: [],
    // workshops: [
    //   {
    //     id: '1',
    //     domain: 'domain',
    //     speaker: 'speaker',
    //     participants: 'nember of participants ',
    //     location:' room',

    //   },
    //   {
    //     id: '2',
    //     image:"",
    //     domain: 'domain',
    //     speaker: 'speaker',
    //     participants: 'nember of participants ',
    //     location:' room',
    //     duration:"",
    //     description:""

    //   },
    //   {
    //     id: '3',
    //     domain: 'domain',
    //     speaker: 'speaker',
    //     participants: 'nember of participants ',
    //     location:' room',

    //   },

    // ],
  },
  {
    id: 2,
    workshop: "Session 2",
    workshops: [],
    // workshops: [
    //   {
    //     id: '1',
    //     domain: 'domain',
    //     speaker: 'speaker',
    //     participants: 'nember of participants ',
    //     location:' room',

    //   },
    //   {
    //     id: '2',
    //     domain: 'domain',
    //     speaker: 'speaker',
    //     participants: 'nember of participants ',
    //     location:' room',

    //   },{
    //     id: '3',
    //     domain: 'domain',
    //     speaker: 'speaker',
    //     participants: 'nember of participants ',
    //     location:' room',

    //   },{
    //     id: '4',
    //     domain: 'domain',
    //     speaker: 'speaker',
    //     participants: 'nember of participants ',
    //     location:' room',

    //   },{
    //     id: '5',
    //     domain: 'domain',
    //     speaker: 'speaker',
    //     participants: 'nember of participants ',
    //     location:' room',

    //   },

    // ],
  },
  {
    id: 3,
    workshop: "Session 3",
    workshops: [],
    // workshops: [
    //   {
    //     id: '1',
    //     domain: 'domain',
    //     speaker: 'speaker',
    //     participants: 'nember of participants ',
    //     location:' room',

    //   },

    // ],
  },
];

const workshopsInfos2 = [
  {
    id: 1,
    workshop: "Session 1",
    workshops: [
      {
        id: 1,
        name: "IOT as a business",
        startDate: "2021-10-18T13:27:52+02:00",
        duration: "1:30",
        location: "Salle César",
        speaker: {
          id: 1,
          firstName: "Mohamed Kadhem",
          lastName: "Belghuith",
          email: "kadhembelghuith@ieee.org",
          image: null,
          phone: null,
          socialMedias: [],
          workshops: [
            1,
            {
              id: 3,
              name: "AI",
              startDate: "2009-02-15T00:00:00+01:00",
              duration: "1:30",
              location: "Salle César",
              speaker: 1,
              domain: {
                id: 1,
                name: "IOT",
                workshops: [1, 3],
                __initializer__: null,
                __cloner__: null,
                __isInitialized__: true,
              },
              users: [],
              session: {
                id: 2,
                workshop: "Session 2",
                workshops: [3],
              },
              numberOfParticipants: null,
              description: null,
            },
          ],
          __initializer__: null,
          __cloner__: null,
          __isInitialized__: true,
        },
        domain: {
          id: 1,
          name: "IOT",
          workshops: [
            1,
            {
              id: 3,
              name: "AI",
              startDate: "2009-02-15T00:00:00+01:00",
              duration: "1:30",
              location: "Salle César",
              speaker: {
                id: 1,
                firstName: "Mohamed Kadhem",
                lastName: "Belghuith",
                email: "kadhembelghuith@ieee.org",
                image: null,
                phone: null,
                socialMedias: [],
                workshops: [1, 3],
                __initializer__: null,
                __cloner__: null,
                __isInitialized__: true,
              },
              domain: 1,
              users: [],
              session: {
                id: 2,
                workshop: "Session 2",
                workshops: [3],
              },
              numberOfParticipants: null,
              description: null,
            },
          ],
          __initializer__: null,
          __cloner__: null,
          __isInitialized__: true,
        },
        users: [
          {
            id: 1,
            fullName: "",
            code: "0",
            username: "",
            idMember: null,
            occupation: null,
            hotel: null,
            roomNumber: null,
            email: "belghuithkadhem@gmail.com",
            sharedWith: null,
            password:
              "$2a$10$NKXe3EyY1GV.wx.A3F44cORxvHHVa2eRsRySB94fK4UF26NU7e1ti",
            image: "test.png",
            cin: "11097828",
            branch: {
              id: 1,
              name: "ENIS Student Branch",
              users: [1],
              __initializer__: null,
              __cloner__: null,
              __isInitialized__: true,
            },
            phone: "26079140",
            roles: ["ROLE_USER"],
            salt: null,
            workshops: [1],
            isEnabled: true,
          },
        ],
        session: 1,
        numberOfParticipants: null,
        description: null,
      },
    ],
  },
  {
    id: 2,
    workshop: "Session 2",
    workshops: [
      {
        id: 3,
        name: "AI",
        startDate: "2009-02-15T00:00:00+01:00",
        duration: "1:30",
        location: "Salle César",
        speaker: {
          id: 1,
          firstName: "Mohamed Kadhem",
          lastName: "Belghuith",
          email: "kadhembelghuith@ieee.org",
          image: null,
          phone: null,
          socialMedias: [],
          workshops: [
            {
              id: 1,
              name: "IOT as a business",
              startDate: "2021-10-18T13:27:52+02:00",
              duration: "1:30",
              location: "Salle César",
              speaker: 1,
              domain: {
                id: 1,
                name: "IOT",
                workshops: [1, 3],
                __initializer__: null,
                __cloner__: null,
                __isInitialized__: true,
              },
              users: [
                {
                  id: 1,
                  fullName: "",
                  code: "0",
                  username: "",
                  idMember: null,
                  occupation: null,
                  hotel: null,
                  roomNumber: null,
                  email: "belghuithkadhem@gmail.com",
                  sharedWith: null,
                  password:
                    "$2a$10$NKXe3EyY1GV.wx.A3F44cORxvHHVa2eRsRySB94fK4UF26NU7e1ti",
                  image: "test.png",
                  cin: "11097828",
                  branch: {
                    id: 1,
                    name: "ENIS Student Branch",
                    users: [1],
                    __initializer__: null,
                    __cloner__: null,
                    __isInitialized__: true,
                  },
                  phone: "26079140",
                  roles: ["ROLE_USER"],
                  salt: null,
                  workshops: [1],
                  isEnabled: true,
                },
              ],
              session: {
                id: 1,
                workshop: "Session 1",
                workshops: [1],
              },
              numberOfParticipants: null,
              description: null,
            },
            3,
          ],
          __initializer__: null,
          __cloner__: null,
          __isInitialized__: true,
        },
        domain: {
          id: 1,
          name: "IOT",
          workshops: [
            {
              id: 1,
              name: "IOT as a business",
              startDate: "2021-10-18T13:27:52+02:00",
              duration: "1:30",
              location: "Salle César",
              speaker: {
                id: 1,
                firstName: "Mohamed Kadhem",
                lastName: "Belghuith",
                email: "kadhembelghuith@ieee.org",
                image: null,
                phone: null,
                socialMedias: [],
                workshops: [1, 3],
                __initializer__: null,
                __cloner__: null,
                __isInitialized__: true,
              },
              domain: 1,
              users: [
                {
                  id: 1,
                  fullName: "",
                  code: "0",
                  username: "",
                  idMember: null,
                  occupation: null,
                  hotel: null,
                  roomNumber: null,
                  email: "belghuithkadhem@gmail.com",
                  sharedWith: null,
                  password:
                    "$2a$10$NKXe3EyY1GV.wx.A3F44cORxvHHVa2eRsRySB94fK4UF26NU7e1ti",
                  image: "test.png",
                  cin: "11097828",
                  branch: {
                    id: 1,
                    name: "ENIS Student Branch",
                    users: [1],
                    __initializer__: null,
                    __cloner__: null,
                    __isInitialized__: true,
                  },
                  phone: "26079140",
                  roles: ["ROLE_USER"],
                  salt: null,
                  workshops: [1],
                  isEnabled: true,
                },
              ],
              session: {
                id: 1,
                workshop: "Session 1",
                workshops: [1],
              },
              numberOfParticipants: null,
              description: null,
            },
            3,
          ],
          __initializer__: null,
          __cloner__: null,
          __isInitialized__: true,
        },
        users: [],
        session: 2,
        numberOfParticipants: null,
        description: null,
      },
    ],
  },
  {
    id: 3,
    workshop: "Session 3",
    workshops: [],
  },
];

export default workshopsInfos2;
